### PR TITLE
Ready to deploy rick cluster

### PR DESCRIPTION
**Pull request by rbo**
Fixed some issues to be ready to deploy rick cluster:
 * Adjust hardware sizing based on [#6](https://github.com/operate-first/hetzner-baremetal-openshift/issues/6#issuecomment-866205831)
 * Setup master with raid #11 
 * Update firewall configurations because of #8 
 * Update documentation

### CODE REVIEW

**Comment by goern** [comment]
@rbo operate-first requires one LGTM and one APPROVED label... 

/cc @tumido

**Comment by rbo** [comment]
@goern 
> @rbo operate-first requires one LGTM and one APPROVED label...

Of course but as far as I know, I can not LGTM my own PR.

**Review by tumido — APPROVED** [review]
/lgtm
/approve

@goern can lgtm and approve as well :stuck_out_tongue:

**Comment by rbo** [comment]
@tumido please have a look, I can not fetch the build details to check out where is the problem.

**Comment by tumido** [comment]
Yeah, me neither. I've pulled the PR and will fix it for you.

**Pull request merged**
