### PR TITLE
Feature/morty issue #16

### PR DESCRIPTION
**Pull request by rbo**
Merge morty changes into main.

### CODE REVIEW

**Comment by rbo** [comment]
I can't open the detail page, got a 504 gateway timeout. Might be related to https://github.com/operate-first/support/issues/673.

I tried to run pre-commit locally:
```
$ pre-commit
Tabs remover.........................................(no files to check)Skipped
Trim Trailing Whitespace.............................(no files to check)Skipped
Check for merge conflicts............................(no files to check)Skipped
Fix End of Files.....................................(no files to check)Skipped
Check for added large files..........................(no files to check)Skipped
Check for case conflicts.............................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key...................................(no files to check)Skipped
yamllint.............................................(no files to check)Skipped
$
```
??? Looks strange...

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
